[workspace]
members = ["crates/*", "auto-shell"]
resolver = "2"


[workspace.dependencies]
auto-lang = { path = "crates/auto-lang" }
auto-val = { path = "crates/auto-val" }
auto-gen = { path = "crates/auto-gen" }
dirs = "6.0.0"
clap = { version = "4.5.17", features = ["derive"] }
rustyline = { version = "14.0.0", features = ["with-file-history"] }
strum = "0.26"
strum_macros = "0.26"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ecow = "0.2.3"
normalize-path = "0.2.1"
regex = "1.11.1"
glob-match = "0.2.1"
roxmltree = "0.18.0"
thiserror = "2.0.12"
miette = { version = "7.2", features = ["fancy"] }
dashmap = "6.1"
blake3 = "1.5"
bincode = "1.3"
