[workspace]
members = ["crates/*"]
resolver = "2"


[workspace.dependencies]
auto-val = { path = "crates/auto-val" }
clap = { version = "4.5.17", features = ["derive"] }
rustyline = { version = "14.0.0", features = ["with-file-history"] }
strum = "0.26"
strum_macros = "0.26"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ecow = "0.2.3"
normalize-path = "0.2.1"

