[package]
name = "auto-val"
version = "0.1.0"
edition = "2021"

[dependencies]
ecow = { workspace = true }
normalize-path = { workspace = true }
regex = { workspace = true }
glob-match = { workspace = true }
thiserror = { workspace = true }
